name: "service-boilerplate"

services:
  backend:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AUTH_PUBLIC_JWK_URI: https://sso.kowlad.ru/realms/minin/protocol/openid-connect/certs
      AUTH_CLIENT_ID: minin-client
      POSTGRES_DB_NAME: postgres
      POSTGRES_DB_USER: minin
      POSTGRES_DB_PASS: minin
      POSTGRES_DB_HOST: backend-database
      POSTGRES_DB_PORT: 5432
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.kowlad.ru`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=leresolver"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    networks:
      - traefik
      - backend
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - backend

  backend-database:
    container_name: "backend-database"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: minin
      POSTGRES_PASSWORD: minin
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped


volumes:
  data:


networks:
  backend:
  traefik:
    name: "traefik-network"
    external: true